/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProcessingVideoIdRouteImport } from './routes/processing.$videoId'
import { Route as LessonVideoIdRouteImport } from './routes/lesson.$videoId'
import { Route as LessonVideoIdQuizRouteImport } from './routes/lesson.$videoId_.quiz'
import { Route as LessonVideoIdPlayerRouteImport } from './routes/lesson.$videoId_.player'
import { Route as LessonVideoIdDoneRouteImport } from './routes/lesson.$videoId_.done'
import { Route as ApiOgVideoIdRouteImport } from './routes/api.og.$videoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingVideoIdRoute = ProcessingVideoIdRouteImport.update({
  id: '/processing/$videoId',
  path: '/processing/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonVideoIdRoute = LessonVideoIdRouteImport.update({
  id: '/lesson/$videoId',
  path: '/lesson/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonVideoIdQuizRoute = LessonVideoIdQuizRouteImport.update({
  id: '/lesson/$videoId_/quiz',
  path: '/lesson/$videoId/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonVideoIdPlayerRoute = LessonVideoIdPlayerRouteImport.update({
  id: '/lesson/$videoId_/player',
  path: '/lesson/$videoId/player',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonVideoIdDoneRoute = LessonVideoIdDoneRouteImport.update({
  id: '/lesson/$videoId_/done',
  path: '/lesson/$videoId/done',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgVideoIdRoute = ApiOgVideoIdRouteImport.update({
  id: '/api/og/$videoId',
  path: '/api/og/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lesson/$videoId': typeof LessonVideoIdRoute
  '/processing/$videoId': typeof ProcessingVideoIdRoute
  '/api/og/$videoId': typeof ApiOgVideoIdRoute
  '/lesson/$videoId/done': typeof LessonVideoIdDoneRoute
  '/lesson/$videoId/player': typeof LessonVideoIdPlayerRoute
  '/lesson/$videoId/quiz': typeof LessonVideoIdQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lesson/$videoId': typeof LessonVideoIdRoute
  '/processing/$videoId': typeof ProcessingVideoIdRoute
  '/api/og/$videoId': typeof ApiOgVideoIdRoute
  '/lesson/$videoId/done': typeof LessonVideoIdDoneRoute
  '/lesson/$videoId/player': typeof LessonVideoIdPlayerRoute
  '/lesson/$videoId/quiz': typeof LessonVideoIdQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lesson/$videoId': typeof LessonVideoIdRoute
  '/processing/$videoId': typeof ProcessingVideoIdRoute
  '/api/og/$videoId': typeof ApiOgVideoIdRoute
  '/lesson/$videoId_/done': typeof LessonVideoIdDoneRoute
  '/lesson/$videoId_/player': typeof LessonVideoIdPlayerRoute
  '/lesson/$videoId_/quiz': typeof LessonVideoIdQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lesson/$videoId'
    | '/processing/$videoId'
    | '/api/og/$videoId'
    | '/lesson/$videoId/done'
    | '/lesson/$videoId/player'
    | '/lesson/$videoId/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lesson/$videoId'
    | '/processing/$videoId'
    | '/api/og/$videoId'
    | '/lesson/$videoId/done'
    | '/lesson/$videoId/player'
    | '/lesson/$videoId/quiz'
  id:
    | '__root__'
    | '/'
    | '/lesson/$videoId'
    | '/processing/$videoId'
    | '/api/og/$videoId'
    | '/lesson/$videoId_/done'
    | '/lesson/$videoId_/player'
    | '/lesson/$videoId_/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LessonVideoIdRoute: typeof LessonVideoIdRoute
  ProcessingVideoIdRoute: typeof ProcessingVideoIdRoute
  ApiOgVideoIdRoute: typeof ApiOgVideoIdRoute
  LessonVideoIdDoneRoute: typeof LessonVideoIdDoneRoute
  LessonVideoIdPlayerRoute: typeof LessonVideoIdPlayerRoute
  LessonVideoIdQuizRoute: typeof LessonVideoIdQuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing/$videoId': {
      id: '/processing/$videoId'
      path: '/processing/$videoId'
      fullPath: '/processing/$videoId'
      preLoaderRoute: typeof ProcessingVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$videoId': {
      id: '/lesson/$videoId'
      path: '/lesson/$videoId'
      fullPath: '/lesson/$videoId'
      preLoaderRoute: typeof LessonVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$videoId_/quiz': {
      id: '/lesson/$videoId_/quiz'
      path: '/lesson/$videoId/quiz'
      fullPath: '/lesson/$videoId/quiz'
      preLoaderRoute: typeof LessonVideoIdQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$videoId_/player': {
      id: '/lesson/$videoId_/player'
      path: '/lesson/$videoId/player'
      fullPath: '/lesson/$videoId/player'
      preLoaderRoute: typeof LessonVideoIdPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$videoId_/done': {
      id: '/lesson/$videoId_/done'
      path: '/lesson/$videoId/done'
      fullPath: '/lesson/$videoId/done'
      preLoaderRoute: typeof LessonVideoIdDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$videoId': {
      id: '/api/og/$videoId'
      path: '/api/og/$videoId'
      fullPath: '/api/og/$videoId'
      preLoaderRoute: typeof ApiOgVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LessonVideoIdRoute: LessonVideoIdRoute,
  ProcessingVideoIdRoute: ProcessingVideoIdRoute,
  ApiOgVideoIdRoute: ApiOgVideoIdRoute,
  LessonVideoIdDoneRoute: LessonVideoIdDoneRoute,
  LessonVideoIdPlayerRoute: LessonVideoIdPlayerRoute,
  LessonVideoIdQuizRoute: LessonVideoIdQuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
